use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ContractError {
    ProjectNotFound = 1,
    Unauthorized = 2,
    ProjectAlreadyExists = 3,
    InvalidRating = 4,
    ReviewNotFound = 5,
    DuplicateReview = 6,
    NotReviewOwner = 7,
    VerificationNotFound = 8,
    InvalidStatus = 9,
    AdminOnly = 10,
    FeeConfigNotSet = 11,
    TreasuryNotSet = 12,
    InsufficientFee = 13,
    InvalidProjectData = 14,
    ProjectNameTooLong = 15,
    InvalidNameFormat = 16,
    CannotRemoveLastAdmin = 17,
    ProjectTooYoung = 18,
    InvalidTag = 19,
    TooManyTags = 20,
    InvalidSocialLink = 21,
    TooManySocialLinks = 22,
    AlreadyReported = 23,
    InvalidReportReason = 24,
    AdminNotFound = 25,
    InvalidProjectName = 26,
    InvalidProjectDesc = 27,
    InvalidCategory = 28,
    ProjectDescTooLong = 29,
    MaxProjectsExceeded = 30,
    InvalidWebsite = 31,
    InvalidLogoCid = 32,
    InvalidMetaCid = 33,
    CategoryTooLong = 34,
    WebsiteTooLong = 35,
    NotRevocable = 36,
    TransferNotFound = 37,
    NotTransferRecip = 38,
    ReviewsDisabled = 39,
    ReviewAlreadyReported = 40,
    ReviewAlreadyHidden = 41,
    ReviewNotHidden = 42,
    AlreadyArchived = 43,
    ProjectNotArchived = 44,
    ReportsCleared = 45,
    CollectionNotFound = 46,
    CollectionExists = 47,
    AlreadyInCollection = 48,
    AlreadyLinked = 49,
    CannotLinkToSelf = 50,
    /// token must be a contract address when verification_fee or registration_fee is non-zero;
    /// native/no-token fee paths are not implemented.
    NativeFeeNotSupported = 51,
}

pub type Error = ContractError;
