use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ContractError {
    AlreadyInitialized = 0,
    NotInitialized = 1,
    NotOwner = 2,
    NotAdmin = 3,
    NotRegistered = 4,
    AlreadyRegistered = 5,
    SlugAlreadyExists = 6,
    InvalidSlug = 7,
    InvalidName = 8,
    InvalidDescription = 9,
    InvalidCategory = 10,
    InvalidWebsite = 11,
    InvalidLogo = 12,
    InvalidMetadata = 13,
    InvalidTags = 14,
    InvalidSocialLinks = 15,
    InvalidLaunchTimestamp = 16,
    MaxProjectsExceeded = 17,
    MaxReviewsExceeded = 18,
    MaxReviewsPerUserExceeded = 19,
    ProjectNotFound = 20,
    NotProjectOwner = 21,
    NotMaintainer = 22,
    AlreadyMaintainer = 23,
    TransferNotRequested = 24,
    TransferAlreadyExists = 25,
    CannotTransferToSelf = 26,
    ClaimNotAllowed = 27,
    AlreadyClaimed = 28,
    InvalidClaimProof = 29,
    InvalidBountyUrl = 30,
    InvalidBountyCid = 31,
    InternalError = 255,
}
